Enhance Dockerfile with CURL validation
Added validation to ensure CURL is installed in the image.

diff --git a/common/Dockerfile b/common/Dockerfile
--- a/common/Dockerfile
+++ b/common/Dockerfile
@@ -50,7 +50,7 @@ COPY --from=dependencies_and_build /app/package.json /app/LICENSE /app/index.js 
 ENV NODE_ENV production
 
 # Validation to confirm that CURL is installed in the final image.
-RUN curl --version
+RUN curl --version || (echo "curl missing" && exit 1)
 
 HEALTHCHECK --interval=1m --timeout=3s \
   CMD curl -f http://localhost:8099/ || exit 1
